name: Render and Deploy Quarto Book

on:
  push:
    branches: [ main ] # Or your default branch
  workflow_dispatch: # Allows manual triggering

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allow checking out code and pushing changes (if needed, e.g., for freezing)
      pages: write    # Allow deploying to GitHub Pages
      id-token: write # Allow OIDC token generation for secure deployment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        # Optionally specify a Quarto version:
        # with:
        #   version: 1.4 # Or 'latest'

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release' # Or specify a version

      - name: Install R Dependencies (with caching)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::data.table
            any::diffobj
            any::here
            any::stringr
            any::lubridate
            any::yaml
            any::knitr
            any::rmarkdown
          cache-version: 1 # Increment cache version if R dependencies change significantly

      - name: Generate Quarto Content
        run: Rscript generate_book.R

      - name: Render Quarto Book
        run: quarto render --profile github-actions # Use a profile if needed, otherwise just `quarto render`

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the _book directory (default output of quarto render for books)
          path: '_book'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4